/**
 * events-auto.js — AUTO-GENERATED by scripts/fetch-recpark-events.js.
 * DO NOT hand-edit. Re-run the script to refresh.
 *
 * Provenance (Integrity Law): every event here carries a `source` field
 * naming the official feed it came from — that feed IS the verification,
 * no personal tap-verify needed. Never add an event to this file by hand;
 * anything hand-entered belongs in src/events.js with a `verified` stamp.
 *
 * Generated: 2026-08-11
 * Source feed: https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar
 */

export const EVENTS_AUTO = [
  {
    "id": "recpark-10068",
    "district": 3,
    "title": "Union Square Daily Programming: Tuesday Blues",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-11",
    "time": "4:00 – 6:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10068",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10045",
    "district": 3,
    "title": "Union Square Daily Programming: Toddler Tuesdays",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-11",
    "time": "10:00 – 11:30 AM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10045",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10114",
    "district": 3,
    "title": "Union square Daily Programming: Wednesday Cardio Dance",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-12",
    "time": "4:00 – 6:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10114",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10091",
    "district": 3,
    "title": "Union Square Daily Programming: Wednesday Tai Chi/Resistance Band Fitness",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-12",
    "time": "8:00 – 9:00 AM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10091",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10160",
    "district": 3,
    "title": "Union Square Daily Programming: Thursday Crafternoons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-13",
    "time": "4:30 – 6:30 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10160",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10137",
    "district": 3,
    "title": "Union Square Daily Programming: Thursday Lunchbreak Music",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-13",
    "time": "11:30 AM – 1:30 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10137",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10206",
    "district": 3,
    "title": "Union Square Daily Programming: Friday Union Square Dances",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-14",
    "time": "5:00 – 8:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10206",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10183",
    "district": 3,
    "title": "Union Square Daily Programming: Friday Chess Lessons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-14",
    "time": "11:30 AM – 1:30 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10183",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10246",
    "district": 3,
    "title": "Union Square Daily Programming: Third Saturday Karaoke",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-15",
    "time": "4:00 – 7:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10246",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10230",
    "district": 3,
    "title": "Union Square Daily Programming: Saturday Juggling Lessons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-15",
    "time": "11:30 AM – 1:30 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10230",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-9976",
    "district": 3,
    "title": "Union Square Daily Programming: Mahjong Lessons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-16",
    "time": "4:00 – 6:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=9976",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-9952",
    "district": 3,
    "title": "Union Square Daily Programming: Sunday Fun Days",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-16",
    "time": "11:00 AM – 2:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=9952",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10023",
    "district": 3,
    "title": "Union Square Daily Programming: Monday Sketching Lessons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-17",
    "time": "4:00 – 6:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10023",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10000",
    "district": 3,
    "title": "Union Square Daily Programming: Imagination Mondays",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-17",
    "time": "10:00 – 11:30 AM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10000",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10069",
    "district": 3,
    "title": "Union Square Daily Programming: Tuesday Blues",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-18",
    "time": "4:00 – 6:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10069",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10046",
    "district": 3,
    "title": "Union Square Daily Programming: Toddler Tuesdays",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-18",
    "time": "10:00 – 11:30 AM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10046",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10115",
    "district": 3,
    "title": "Union square Daily Programming: Wednesday Cardio Dance",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-19",
    "time": "4:00 – 6:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10115",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10092",
    "district": 3,
    "title": "Union Square Daily Programming: Wednesday Tai Chi/Resistance Band Fitness",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-19",
    "time": "8:00 – 9:00 AM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10092",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10161",
    "district": 3,
    "title": "Union Square Daily Programming: Thursday Crafternoons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-20",
    "time": "4:30 – 6:30 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10161",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10138",
    "district": 3,
    "title": "Union Square Daily Programming: Thursday Lunchbreak Music",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-20",
    "time": "11:30 AM – 1:30 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10138",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10207",
    "district": 3,
    "title": "Union Square Daily Programming: Friday Union Square Dances",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-21",
    "time": "5:00 – 8:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10207",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10184",
    "district": 3,
    "title": "Union Square Daily Programming: Friday Chess Lessons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-21",
    "time": "11:30 AM – 1:30 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10184",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10257",
    "district": 3,
    "title": "Union Square Daily Programming: Saturday Cinema on the Square",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-22",
    "time": "6:00 – 10:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10257",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10231",
    "district": 3,
    "title": "Union Square Daily Programming: Saturday Juggling Lessons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-22",
    "time": "11:30 AM – 1:30 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10231",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-9977",
    "district": 3,
    "title": "Union Square Daily Programming: Mahjong Lessons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-23",
    "time": "4:00 – 6:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=9977",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-9953",
    "district": 3,
    "title": "Union Square Daily Programming: Sunday Fun Days",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-23",
    "time": "11:00 AM – 2:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=9953",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10024",
    "district": 3,
    "title": "Union Square Daily Programming: Monday Sketching Lessons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-24",
    "time": "4:00 – 6:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10024",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10001",
    "district": 3,
    "title": "Union Square Daily Programming: Imagination Mondays",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-24",
    "time": "10:00 – 11:30 AM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10001",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10070",
    "district": 3,
    "title": "Union Square Daily Programming: Tuesday Blues",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-25",
    "time": "4:00 – 6:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10070",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10047",
    "district": 3,
    "title": "Union Square Daily Programming: Toddler Tuesdays",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-25",
    "time": "10:00 – 11:30 AM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10047",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10116",
    "district": 3,
    "title": "Union square Daily Programming: Wednesday Cardio Dance",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-26",
    "time": "4:00 – 6:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10116",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10093",
    "district": 3,
    "title": "Union Square Daily Programming: Wednesday Tai Chi/Resistance Band Fitness",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-26",
    "time": "8:00 – 9:00 AM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10093",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10162",
    "district": 3,
    "title": "Union Square Daily Programming: Thursday Crafternoons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-27",
    "time": "4:30 – 6:30 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10162",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10139",
    "district": 3,
    "title": "Union Square Daily Programming: Thursday Lunchbreak Music",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-27",
    "time": "11:30 AM – 1:30 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10139",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10208",
    "district": 3,
    "title": "Union Square Daily Programming: Friday Union Square Dances",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-28",
    "time": "5:00 – 8:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10208",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10185",
    "district": 3,
    "title": "Union Square Daily Programming: Friday Chess Lessons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-28",
    "time": "11:30 AM – 1:30 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10185",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10232",
    "district": 3,
    "title": "Union Square Daily Programming: Saturday Juggling Lessons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-29",
    "time": "11:30 AM – 1:30 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10232",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-9978",
    "district": 3,
    "title": "Union Square Daily Programming: Mahjong Lessons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-30",
    "time": "4:00 – 6:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=9978",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-9954",
    "district": 3,
    "title": "Union Square Daily Programming: Sunday Fun Days",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-30",
    "time": "11:00 AM – 2:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=9954",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10025",
    "district": 3,
    "title": "Union Square Daily Programming: Monday Sketching Lessons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-31",
    "time": "4:00 – 6:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10025",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10002",
    "district": 3,
    "title": "Union Square Daily Programming: Imagination Mondays",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-08-31",
    "time": "10:00 – 11:30 AM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10002",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10071",
    "district": 3,
    "title": "Union Square Daily Programming: Tuesday Blues",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-01",
    "time": "4:00 – 6:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10071",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10421",
    "district": 4,
    "title": "Chair Yoga",
    "venue": "Sunset Dunes - Great Highway, between Lincoln and Sloat San Francisco CA 94122",
    "date": "2026-09-01",
    "time": "2:00 – 3:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10421",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10048",
    "district": 3,
    "title": "Union Square Daily Programming: Toddler Tuesdays",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-01",
    "time": "10:00 – 11:30 AM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10048",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10117",
    "district": 3,
    "title": "Union square Daily Programming: Wednesday Cardio Dance",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-02",
    "time": "4:00 – 6:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10117",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10094",
    "district": 3,
    "title": "Union Square Daily Programming: Wednesday Tai Chi/Resistance Band Fitness",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-02",
    "time": "8:00 – 9:00 AM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10094",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10163",
    "district": 3,
    "title": "Union Square Daily Programming: Thursday Crafternoons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-03",
    "time": "4:30 – 6:30 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10163",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10140",
    "district": 3,
    "title": "Union Square Daily Programming: Thursday Lunchbreak Music",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-03",
    "time": "11:30 AM – 1:30 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10140",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10209",
    "district": 3,
    "title": "Union Square Daily Programming: Friday Union Square Dances",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-04",
    "time": "5:00 – 8:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10209",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10186",
    "district": 3,
    "title": "Union Square Daily Programming: Friday Chess Lessons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-04",
    "time": "11:30 AM – 1:30 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10186",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10233",
    "district": 3,
    "title": "Union Square Daily Programming: Saturday Juggling Lessons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-05",
    "time": "11:30 AM – 1:30 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10233",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-9979",
    "district": 3,
    "title": "Union Square Daily Programming: Mahjong Lessons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-06",
    "time": "4:00 – 6:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=9979",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-9955",
    "district": 3,
    "title": "Union Square Daily Programming: Sunday Fun Days",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-06",
    "time": "11:00 AM – 2:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=9955",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10026",
    "district": 3,
    "title": "Union Square Daily Programming: Monday Sketching Lessons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-07",
    "time": "4:00 – 6:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10026",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10003",
    "district": 3,
    "title": "Union Square Daily Programming: Imagination Mondays",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-07",
    "time": "10:00 – 11:30 AM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10003",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10072",
    "district": 3,
    "title": "Union Square Daily Programming: Tuesday Blues",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-08",
    "time": "4:00 – 6:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10072",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10049",
    "district": 3,
    "title": "Union Square Daily Programming: Toddler Tuesdays",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-08",
    "time": "10:00 – 11:30 AM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10049",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10118",
    "district": 3,
    "title": "Union square Daily Programming: Wednesday Cardio Dance",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-09",
    "time": "4:00 – 6:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10118",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10095",
    "district": 3,
    "title": "Union Square Daily Programming: Wednesday Tai Chi/Resistance Band Fitness",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-09",
    "time": "8:00 – 9:00 AM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10095",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10164",
    "district": 3,
    "title": "Union Square Daily Programming: Thursday Crafternoons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-10",
    "time": "4:30 – 6:30 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10164",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10141",
    "district": 3,
    "title": "Union Square Daily Programming: Thursday Lunchbreak Music",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-10",
    "time": "11:30 AM – 1:30 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10141",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10210",
    "district": 3,
    "title": "Union Square Daily Programming: Friday Union Square Dances",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-11",
    "time": "5:00 – 8:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10210",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10187",
    "district": 3,
    "title": "Union Square Daily Programming: Friday Chess Lessons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-11",
    "time": "11:30 AM – 1:30 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10187",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10234",
    "district": 3,
    "title": "Union Square Daily Programming: Saturday Juggling Lessons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-12",
    "time": "11:30 AM – 1:30 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10234",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10405",
    "district": 4,
    "title": "Zumba and Shake The Fog",
    "venue": "Sunset Dunes - Great Highway, between Lincoln and Sloat San Francisco CA 94122",
    "date": "2026-09-12",
    "time": "10:30 – 11:15 AM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10405",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-9980",
    "district": 3,
    "title": "Union Square Daily Programming: Mahjong Lessons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-13",
    "time": "4:00 – 6:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=9980",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10417",
    "district": 4,
    "title": "Sunset Dunes Community Cleanup",
    "venue": "Sunset Dunes and Upper Great Highway - 1611 Upper Great Highway San Francisco CA 94122",
    "date": "2026-09-13",
    "time": "1:00 – 3:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10417",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10411",
    "district": 4,
    "title": "2nd Sunday Serenades",
    "venue": "Sunset Dunes - Great Highway, between Lincoln and Sloat San Francisco CA 94122",
    "date": "2026-09-13",
    "time": "12:00 – 2:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10411",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-9956",
    "district": 3,
    "title": "Union Square Daily Programming: Sunday Fun Days",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-13",
    "time": "11:00 AM – 2:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=9956",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10027",
    "district": 3,
    "title": "Union Square Daily Programming: Monday Sketching Lessons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-14",
    "time": "4:00 – 6:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10027",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10004",
    "district": 3,
    "title": "Union Square Daily Programming: Imagination Mondays",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-14",
    "time": "10:00 – 11:30 AM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10004",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10073",
    "district": 3,
    "title": "Union Square Daily Programming: Tuesday Blues",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-15",
    "time": "4:00 – 6:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10073",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10050",
    "district": 3,
    "title": "Union Square Daily Programming: Toddler Tuesdays",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-15",
    "time": "10:00 – 11:30 AM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10050",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10119",
    "district": 3,
    "title": "Union square Daily Programming: Wednesday Cardio Dance",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-16",
    "time": "4:00 – 6:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10119",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10096",
    "district": 3,
    "title": "Union Square Daily Programming: Wednesday Tai Chi/Resistance Band Fitness",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-16",
    "time": "8:00 – 9:00 AM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10096",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10165",
    "district": 3,
    "title": "Union Square Daily Programming: Thursday Crafternoons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-17",
    "time": "4:30 – 6:30 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10165",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10142",
    "district": 3,
    "title": "Union Square Daily Programming: Thursday Lunchbreak Music",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-17",
    "time": "11:30 AM – 1:30 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10142",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10211",
    "district": 3,
    "title": "Union Square Daily Programming: Friday Union Square Dances",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-18",
    "time": "5:00 – 8:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10211",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10188",
    "district": 3,
    "title": "Union Square Daily Programming: Friday Chess Lessons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-18",
    "time": "11:30 AM – 1:30 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10188",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10247",
    "district": 3,
    "title": "Union Square Daily Programming: Third Saturday Karaoke",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-19",
    "time": "4:00 – 7:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10247",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10235",
    "district": 3,
    "title": "Union Square Daily Programming: Saturday Juggling Lessons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-19",
    "time": "11:30 AM – 1:30 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10235",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-9981",
    "district": 3,
    "title": "Union Square Daily Programming: Mahjong Lessons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-20",
    "time": "4:00 – 6:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=9981",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-9957",
    "district": 3,
    "title": "Union Square Daily Programming: Sunday Fun Days",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-20",
    "time": "11:00 AM – 2:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=9957",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10028",
    "district": 3,
    "title": "Union Square Daily Programming: Monday Sketching Lessons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-21",
    "time": "4:00 – 6:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10028",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10005",
    "district": 3,
    "title": "Union Square Daily Programming: Imagination Mondays",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-21",
    "time": "10:00 – 11:30 AM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10005",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10074",
    "district": 3,
    "title": "Union Square Daily Programming: Tuesday Blues",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-22",
    "time": "4:00 – 6:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10074",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10051",
    "district": 3,
    "title": "Union Square Daily Programming: Toddler Tuesdays",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-22",
    "time": "10:00 – 11:30 AM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10051",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10120",
    "district": 3,
    "title": "Union square Daily Programming: Wednesday Cardio Dance",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-23",
    "time": "4:00 – 6:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10120",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10097",
    "district": 3,
    "title": "Union Square Daily Programming: Wednesday Tai Chi/Resistance Band Fitness",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-23",
    "time": "8:00 – 9:00 AM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10097",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10166",
    "district": 3,
    "title": "Union Square Daily Programming: Thursday Crafternoons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-24",
    "time": "4:30 – 6:30 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10166",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10143",
    "district": 3,
    "title": "Union Square Daily Programming: Thursday Lunchbreak Music",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-24",
    "time": "11:30 AM – 1:30 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10143",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10212",
    "district": 3,
    "title": "Union Square Daily Programming: Friday Union Square Dances",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-25",
    "time": "5:00 – 8:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10212",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10189",
    "district": 3,
    "title": "Union Square Daily Programming: Friday Chess Lessons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-25",
    "time": "11:30 AM – 1:30 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10189",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10258",
    "district": 3,
    "title": "Union Square Daily Programming: Saturday Cinema on the Square",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-26",
    "time": "6:00 – 10:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10258",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10236",
    "district": 3,
    "title": "Union Square Daily Programming: Saturday Juggling Lessons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-26",
    "time": "11:30 AM – 1:30 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10236",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-9982",
    "district": 3,
    "title": "Union Square Daily Programming: Mahjong Lessons",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-27",
    "time": "4:00 – 6:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=9982",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-9958",
    "district": 3,
    "title": "Union Square Daily Programming: Sunday Fun Days",
    "venue": "Union Square - Post and Stockton San Francisco CA 94108",
    "date": "2026-09-27",
    "time": "11:00 AM – 2:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=9958",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  },
  {
    "id": "recpark-10422",
    "district": 4,
    "title": "Chair Yoga",
    "venue": "Sunset Dunes - Great Highway, between Lincoln and Sloat San Francisco CA 94122",
    "date": "2026-10-01",
    "time": "2:00 – 3:00 PM",
    "url": "https://sfrecpark.org/calendar.aspx?EID=10422",
    "source": "SF Rec & Parks iCal — https://sfrecpark.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"
  }
];
